## Q1. Sensor readings

Given the temperature readings and an average measurement error of +2°C, perform the operations using vectorization and Boolean indexing.

In [ ]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2
print("a. Readings after adding 2°C:", corrected_temperature)

fahrenheit = corrected_temperature * 9 / 5 + 32
print("b. Temperatures in Fahrenheit:", fahrenheit)

readings_above_32 = corrected_temperature[corrected_temperature > 32]
print("c. Readings greater than 32°C:", readings_above_32)

count_above_32 = np.sum(corrected_temperature > 32)
print("d. Number of readings greater than 32°C:", count_above_32)

a. Readings after adding 2°C: [27 30 33 37 40 29 35 42]
b. Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
c. Readings greater than 32°C: [33 37 40 35 42]
d. Number of readings greater than 32°C: 5


**e. Explanation:** Vectorization applies an operation to an entire NumPy array without writing an explicit loop. Boolean indexing selects elements that satisfy a condition. These approaches make code shorter and often faster because NumPy performs the operations in optimized array routines.

## Q2. Daily steps

The matrix contains the daily step counts of four users over three days.

In [ ]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("a. Total steps recorded:", np.sum(steps))
print("b. Mean number of steps:", np.mean(steps))
print("c. Maximum steps:", np.max(steps))
print("   Minimum steps:", np.min(steps))
print("d. Total steps for each day (axis=0):", np.sum(steps, axis=0))
print("e. Total steps for each user (axis=1):", np.sum(steps, axis=1))

max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("f. Maximum step count position (user index, day index):", max_position)
print("   Maximum step count:", steps[max_position])

a. Total steps recorded: 84200
b. Mean number of steps: 7016.666666666667
c. Maximum steps: 9500
   Minimum steps: 4500
d. Total steps for each day (axis=0): [26500 27300 30400]
e. Total steps for each user (axis=1): [18300 24500 14400 27000]
f. Maximum step count position (user index, day index): (np.int64(3), np.int64(2))
   Maximum step count: 9500


## Q3. NumPy slicing, copying, reshaping, and flattening

In [ ]:
original = np.array([1, 2, 3, 4, 5, 6])
print("a. Original array:", original)

subset = original[1:5]
print("b. subset:", subset)

subset[0] = 999
print("c. Original after modifying subset:", original)
print("   Modified subset:", subset)

copied_array = original[1:5].copy()
copied_array[0] = 500
print("d. Original after modifying copied array:", original)
print("   Copied array:", copied_array)

matrix = np.arange(1, 13).reshape(3, 4)
print("e. 3 x 4 matrix:")
print(matrix)

print("f. First row:", matrix[0, :])
print("   Last row:", matrix[-1, :])
print("   Second column:", matrix[:, 1])
print("   Rows 1–2 and columns 2–3 (1-based wording):")
print(matrix[1:3, 1:3])

flat_array = matrix.flatten()
ravel_array = matrix.ravel()
print("g. flatten():", flat_array)
print("   ravel():", ravel_array)

ravel_array[0] = 100
print("h. Matrix after modifying ravel result:")
print(matrix)

flat_array[1] = 200
print("i. Matrix after modifying flatten result:")
print(matrix)

print("j. Shape:", matrix.shape)
print("   Dimensions (ndim):", matrix.ndim)
print("   Number of elements (size):", matrix.size)
print("   Data type (dtype):", matrix.dtype)

a. Original array: [1 2 3 4 5 6]
b. subset: [2 3 4 5]
c. Original after modifying subset: [  1 999   3   4   5   6]
   Modified subset: [999   3   4   5]
d. Original after modifying copied array: [  1 999   3   4   5   6]
   Copied array: [500   3   4   5]
e. 3 x 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
f. First row: [1 2 3 4]
   Last row: [ 9 10 11 12]
   Second column: [ 2  6 10]
   Rows 1–2 and columns 2–3 (1-based wording):
[[ 6  7]
 [10 11]]
g. flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
   ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
h. Matrix after modifying ravel result:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
i. Matrix after modifying flatten result:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
j. Shape: (3, 4)
   Dimensions (ndim): 2
   Number of elements (size): 12
   Data type (dtype): int64


## Q4. Predicting an assistance score

Each row of `X` represents a user. The columns represent sleep hours, activity level, and stress level. The coefficient vector is calculated using the Ordinary Least Squares equation given in the assignment.

In [ ]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("a. Shape of X:", X.shape)
print("   Dimensions of X:", X.ndim)

X_transpose = X.T
print("\nb. X.T:")
print(X_transpose)
print("The transpose swaps rows and columns, so each feature becomes a row.")

XTX = X_transpose @ X
print("\nc. X.T @ X:")
print(XTX)

print("\nd. Inverse of X.T @ X:")
XTX_inverse = np.linalg.inv(XTX)
print(XTX_inverse)

beta = XTX_inverse @ X_transpose @ y
print("\ne. OLS coefficients (beta):")
print(beta)

print("\nf. Coefficient interpretation:")
print("Sleep-hours coefficient:", beta[0])
print("Activity-level coefficient:", beta[1])
print("Stress-level coefficient:", beta[2])
print("Each coefficient represents the model's change in predicted score for a one-unit increase in that feature, holding the other features constant.")

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("\ng. New user's predicted assistance score:", predicted_score)

a. Shape of X: (4, 3)
   Dimensions of X: 2

b. X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
The transpose swaps rows and columns, so each feature becomes a row.

c. X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

d. Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

e. OLS coefficients (beta):
[-0.15921454  0.14083853 10.06302242]

f. Coefficient interpretation:
Sleep-hours coefficient: -0.15921454159465398
Activity-level coefficient: 0.14083852991906243
Stress-level coefficient: 10.063022422714587
Each coefficient represents the model's change in predicted score for a one-unit increase in that feature, holding the other features constant.

g. New user's predicted assistance score: 75.27862544779134
